( function( wp ) {
  'use strict';
  var el=wp.element.createElement, Fragment=wp.element.Fragment, __=wp.i18n.__;
  var register=wp.blocks.registerBlockType, useBlockProps=wp.blockEditor.useBlockProps, Inspector=wp.blockEditor.InspectorControls, MediaUpload=wp.blockEditor.MediaUpload, Check=wp.blockEditor.MediaUploadCheck;
  var Panel=wp.components.PanelBody, Button=wp.components.Button, Text=wp.components.TextControl, Area=wp.components.TextareaControl, Toggle=wp.components.ToggleControl, Range=wp.components.RangeControl, SSR=wp.serverSideRender.default||wp.serverSideRender;
  function mediaButton(label,value,onSelect){return el(Check,{},el(MediaUpload,{allowedTypes:['image'],multiple:false,value:value,onSelect:onSelect,render:function(p){return el(Button,{variant:'secondary',onClick:p.open},label);}}));}
  register('nntm/dieu-thuong',{edit:function(props){var a=props.attributes,set=props.setAttributes,slides=Array.isArray(a.slides)?a.slides:[],gallery=Array.isArray(a.gallery)?a.gallery:[];
    function update(list,key,index,patch){var next=list.slice();next[index]=Object.assign({},next[index],patch);var out={};out[key]=next;set(out);}
    function repeater(list,key,title){return list.map(function(item,i){return el(Panel,{title:title+' '+(i+1),initialOpen:i===0,key:key+i},mediaButton(__('Chọn/đổi ảnh','nntm'),item.imageId,function(m){update(list,key,i,{imageId:m.id||0,imageUrl:m.url||'',imageAlt:m.alt||''});}),key==='slides'?el(Fragment,{},el(Text,{label:'Tiêu đề',value:item.heading||'',onChange:function(v){update(list,key,i,{heading:v});}}),el(Area,{label:'Mô tả',value:item.text||'',onChange:function(v){update(list,key,i,{text:v});}})):null,el(Button,{isDestructive:true,variant:'link',onClick:function(){var n=list.slice();n.splice(i,1);var o={};o[key]=n;set(o);}},'Xóa ảnh'));});}
    return el('div',useBlockProps(),el(Inspector,{},el(Panel,{title:'Mở đầu',initialOpen:true},el(Text,{label:'Tiêu đề',value:a.heading,onChange:function(v){set({heading:v});}}),el(Text,{label:'Dòng nhấn',value:a.introTitle,onChange:function(v){set({introTitle:v});}}),el(Area,{label:'Mô tả',value:a.introText,onChange:function(v){set({introText:v});}})),el(Panel,{title:'Slider',initialOpen:true},repeater(slides,'slides','Slide'),el(Button,{variant:'primary',onClick:function(){set({slides:slides.concat([{imageId:0,imageUrl:'',imageAlt:'',heading:'Tiêu đề banner',text:'Nội dung mô tả'}])});}},'Thêm slide'),el(Toggle,{label:'Tự động chạy',checked:!!a.autoplay,onChange:function(v){set({autoplay:v});}}),el(Range,{label:'Chu kỳ (giây)',min:3,max:20,value:a.interval,onChange:function(v){set({interval:v});}})),el(Panel,{title:'Câu chuyện',initialOpen:false},mediaButton('Chọn ảnh nền núi',a.bannerImageId,function(m){set({bannerImageId:m.id||0,bannerImageUrl:m.url||''});}),mediaButton('Chọn ảnh tròn',a.portraitImageId,function(m){set({portraitImageId:m.id||0,portraitImageUrl:m.url||''});}),el(Text,{label:'Tiêu đề',value:a.storyHeading,onChange:function(v){set({storyHeading:v});}}),el(Area,{label:'Đoạn trên',value:a.storyTextTop,onChange:function(v){set({storyTextTop:v});}}),repeater(gallery,'gallery','Ảnh nội dung'),gallery.length<3?el(Button,{variant:'primary',onClick:function(){set({gallery:gallery.concat([{imageId:0,imageUrl:'',imageAlt:''}])});}},'Thêm ảnh'):null,el(Area,{label:'Đoạn dưới',value:a.storyTextBottom,onChange:function(v){set({storyTextBottom:v});}}),el(Text,{label:'Nhãn nút',value:a.ctaLabel,onChange:function(v){set({ctaLabel:v});}}),el(Text,{label:'Liên kết nút',value:a.ctaUrl,onChange:function(v){set({ctaUrl:v});}}))),el(SSR,{block:'nntm/dieu-thuong',attributes:a}));},save:function(){return null;}});
} )(window.wp);
