<?php
/**
 * Dynamic render for nntm/floating-video.
 *
 * Behaviour:
 * - Source can be a WordPress Media Library video or an external URL.
 * - External URL supports YouTube, Vimeo and direct HTML5 video files.
 * - Playback is autoplay + muted + loop + playsinline.
 * - The whole media area links to the configured related post.
 * - The front-end contains no visible controls/buttons from this block.
 */

/** @var array $attributes */

defined( 'ABSPATH' ) || exit;

$source_type = isset( $attributes['sourceType'] ) ? sanitize_key( (string) $attributes['sourceType'] ) : 'library';
if ( ! in_array( $source_type, array( 'library', 'url' ), true ) ) {
	$source_type = 'library';
}

$video_id  = isset( $attributes['videoId'] ) ? absint( $attributes['videoId'] ) : 0;
$video_url = isset( $attributes['videoUrl'] ) ? esc_url_raw( (string) $attributes['videoUrl'] ) : '';

if ( 'library' === $source_type && $video_id > 0 ) {
	$mime = (string) get_post_mime_type( $video_id );
	if ( 0 === strpos( $mime, 'video/' ) ) {
		$library_url = wp_get_attachment_url( $video_id );
		if ( is_string( $library_url ) && '' !== $library_url ) {
			$video_url = esc_url_raw( $library_url );
		}
	} else {
		$video_url = '';
	}
}

if ( '' === $video_url ) {
	return;
}

$linked_post_id = isset( $attributes['linkedPostId'] ) ? absint( $attributes['linkedPostId'] ) : 0;
$linked_post    = $linked_post_id > 0 ? get_post( $linked_post_id ) : null;
$linked_url     = $linked_post instanceof WP_Post ? get_permalink( $linked_post ) : '';
$linked_title   = $linked_post instanceof WP_Post ? get_the_title( $linked_post ) : '';

if ( ! is_string( $linked_url ) ) {
	$linked_url = '';
}

$media_type               = 'html5';
$embed_url                = '';
$youtube_poster_url       = '';
$youtube_poster_fallback  = '';
$host                     = strtolower( (string) wp_parse_url( $video_url, PHP_URL_HOST ) );
$path                     = (string) wp_parse_url( $video_url, PHP_URL_PATH );
$query                    = (string) wp_parse_url( $video_url, PHP_URL_QUERY );

// YouTube: watch, youtu.be, shorts, live and embed URLs.
$youtube_hosts = array(
	'youtube.com',
	'www.youtube.com',
	'm.youtube.com',
	'youtu.be',
	'www.youtu.be',
	'youtube-nocookie.com',
	'www.youtube-nocookie.com',
);

if ( in_array( $host, $youtube_hosts, true ) ) {
	$youtube_id = '';

	if ( 'youtu.be' === $host || 'www.youtu.be' === $host ) {
		if ( preg_match( '#^/([A-Za-z0-9_-]{11})(?:/|$)#', $path, $matches ) ) {
			$youtube_id = $matches[1];
		}
	} else {
		parse_str( $query, $query_args );
		if ( isset( $query_args['v'] ) && is_string( $query_args['v'] ) ) {
			$youtube_id = $query_args['v'];
		}

		if ( '' === $youtube_id && preg_match( '#/(?:embed|shorts|live)/([A-Za-z0-9_-]{11})#', $path, $matches ) ) {
			$youtube_id = $matches[1];
		}
	}

	if ( preg_match( '/^[A-Za-z0-9_-]{11}$/', $youtube_id ) ) {
		$media_type = 'youtube';
		$embed_url  = add_query_arg(
			array(
				'autoplay'       => '1',
				'mute'           => '1',
				'loop'           => '1',
				'playlist'       => $youtube_id,
				'controls'       => '0',
				'playsinline'     => '1',
				'rel'            => '0',
				'disablekb'      => '1',
				'fs'             => '0',
				'iv_load_policy' => '3',
				'cc_load_policy' => '0',
			),
			'https://www.youtube-nocookie.com/embed/' . rawurlencode( $youtube_id )
		);

		// Cover the YouTube player's initial chrome while autoplay starts.
		$youtube_poster_url      = 'https://i.ytimg.com/vi/' . rawurlencode( $youtube_id ) . '/maxresdefault.jpg';
		$youtube_poster_fallback = 'https://i.ytimg.com/vi/' . rawurlencode( $youtube_id ) . '/mqdefault.jpg';
	}
}

// Vimeo public video URLs.
if ( 'html5' === $media_type && in_array( $host, array( 'vimeo.com', 'www.vimeo.com', 'player.vimeo.com' ), true ) ) {
	$vimeo_id = '';
	if ( preg_match( '#/(?:video/)?([0-9]+)(?:/|$)#', $path, $matches ) ) {
		$vimeo_id = $matches[1];
	}

	if ( '' !== $vimeo_id ) {
		$media_type = 'vimeo';
		$embed_url  = add_query_arg(
			array(
				'autoplay'   => '1',
				'muted'      => '1',
				'loop'       => '1',
				'background' => '1',
				'title'      => '0',
				'byline'     => '0',
				'portrait'   => '0',
			),
			'https://player.vimeo.com/video/' . rawurlencode( $vimeo_id )
		);
	}
}

$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class'           => 'nntm-floating-video',
		'data-media-type' => $media_type,
	)
);

$link_label = '' !== trim( $linked_title )
	? sprintf( __( 'Mở bài viết: %s', 'nntm' ), wp_strip_all_tags( $linked_title ) )
	: __( 'Mở bài viết liên quan', 'nntm' );
?>
<aside <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput -- generated by WordPress. ?>>
	<div class="nntm-floating-video__media">
		<?php if ( in_array( $media_type, array( 'youtube', 'vimeo' ), true ) && '' !== $embed_url ) : ?>
			<iframe
				class="nntm-floating-video__iframe"
				src="<?php echo esc_url( $embed_url ); ?>"
				title="<?php esc_attr_e( 'Video tự phát', 'nntm' ); ?>"
				allow="autoplay; encrypted-media"
				referrerpolicy="strict-origin-when-cross-origin"
				loading="eager"
				tabindex="-1"
				aria-hidden="true"
			></iframe>
		<?php else : ?>
			<video
				class="nntm-floating-video__video"
				src="<?php echo esc_url( $video_url ); ?>"
				autoplay
				muted
				loop
				playsinline
				preload="auto"
				disablepictureinpicture
				tabindex="-1"
				aria-hidden="true"
			></video>
		<?php endif; ?>

		<?php if ( 'youtube' === $media_type && '' !== $youtube_poster_url ) : ?>
			<img
				class="nntm-floating-video__youtube-cover"
				src="<?php echo esc_url( $youtube_poster_url ); ?>"
				data-fallback-src="<?php echo esc_url( $youtube_poster_fallback ); ?>"
				alt=""
				loading="eager"
				decoding="async"
				aria-hidden="true"
			>
		<?php endif; ?>

		<?php if ( '' !== $linked_url ) : ?>
			<a
				class="nntm-floating-video__link"
				href="<?php echo esc_url( $linked_url ); ?>"
				aria-label="<?php echo esc_attr( $link_label ); ?>"
			></a>
		<?php endif; ?>
	</div>
</aside>
